onflow/flow-go-sdk

README.md
=> Update SDK path in Readme examples.

README.md
Closes: #???
Helping hand to update the very first code example. Please feel free to close if there's already ongoing work to update the examples. My first thought was to test the actual examples from the README.md. It didn't occur to me to check out the actual examples first though (which are updated properly).
______
=> Update "Create an Account" sample code

client/client.go
This PR adds a short description for the `client` package.
=> Client: Add godoc comment for client package

client/convert/protobuf.go, go.mod, go.sum, transaction.go, transaction_test.go
This PR is a stop-gap measure to allow the SDK to be compatible with the new transaction format, which includes arguments, before arguments are fully implemented. This allows us to avoid a breaking change in the future.
=> Add placeholder for transaction arguments

account.go
Sets the `AccountKey` Signature field automatically when setting the public key
=> Set the algo when setting the pub key

examples/create_account/main.go, examples/deploy_contract/main.go, examples/examples.go
This PR updates the emulator examples to be compatible with the upcoming emulator release.
=> Update examples to be compatible with new emulator

client/client.go, client/client_test.go, client/convert/protobuf.go, client/convert/protobuf_test.go, test/entities.go, test/greetings.go, transaction.go, transaction_test.go
This PR adds SDK support for transaction arguments.
- Add `Arguments` field to `flow.Transaction`
- Add `AddArgument` method to `flow.Transaction`
- Include arguments in protobuf messages, update convert functions & tests
=> Transaction arguments

examples/README.md, examples/transaction_arguments/main.go, test/greetings.go
This PR adds a script that demonstrates how to use transaction arguments.
The script sends a modified version of `"Hello, World!"` that uses a greeting randomly picked from a variety of languages.
```
Sending transaction:
----------------
Script:
transaction(greeting: String) {
execute { 
log(greeting.concat(", World!")) 
}
}
Arguments:
greeting: Hallo
----------------
```
This example is compatible with the emulator version in this branch: https://github.com/dapperlabs/flow-emulator/pull/68
=> Transaction arguments example

go.mod, go.sum
- Bump `onflow/cadence` to `v0.4.0`
=> Upgrade Cadence to v0.4.0

go.mod, go.sum, transaction.go
Closes: #56 
This PR introduces the following changes:
- Update to latest Access API protobuf definitions
- Add `flow.TransactionStatusExpired` constant
=> Add flow.TransactionStatusExpired constant

collection.go, event.go, flow.go, go.mod, go.sum, transaction.go
Changelog:
- Thread-safe entity hasher: #55 
- Add `flow.TransactionStatusExpired`: #57
=> Version 0.5.0

client/client.go, client/client_test.go, client/errors.go
Version 0.6.0 includes the following changes:
- Improved RPC errors in `client` package: https://github.com/onflow/flow-go-sdk/pull/62
- Removed `crypto.KeyType` enum: https://github.com/onflow/flow-go-sdk/pull/58
=> Version 0.6.0

go.mod, go.sum
Update Cadence to v0.5.1, which contains an important bugfix (onflow/cadence#227)
=> Upgrade to Cadence v0.5.1

examples/Makefile, examples/README.md
This PR cleans up the `examples` package to make it easier to run examples.
=> examples: Add Makefile, clean up README

README.md
Add precision about ECDSA in the README file.
______
=> Minor ECDSA update

client/mock_client_test.go, go.mod, go.sum
Use the released version instead of pinning a version.
=> Update onflow/flow/protobuf/go/flow to v0.1.5

examples/cloudkms/main.go
Closes: #???
One of the examples in the cloudkms examples isn't compiling, causing the build on master to fail
______
=> ID -> Index

crypto/cloudkms/cloudkms.go, crypto/cloudkms/cloudkms_test.go
Closes: N/A
Adds json tag to key struct, for more idiomatic json marshalling
Adds KeyFromResourceID to be able to parse the key struct from a resource ID
Both of these changes will be used in the flow-cli
______
=> Add json tags to key struct and KeyFromResourceID func

account.go, client/client.go, client/convert/protobuf.go, examples/deploy_contract/main.go, examples/examples.go, examples/query_events/main.go, examples/transaction_signing/multi_party/main.go, examples/transaction_signing/multi_party_multisig/main.go, examples/transaction_signing/multi_party_two_authorizers/main.go, examples/transaction_signing/single_party/main.go, examples/transaction_signing/single_party_multisig/main.go, go.mod, go.sum, templates/accounts.go, test/entities.go
References: https://github.com/dapperlabs/flow-go/issues/4806
______
=> Multiple smart contract support

examples/examples.go
I saw you use Handle() to handle errors,so I unified the code style,and cut out some extra blank lines
=> [optimize]opt err handle

client/client.go
The code is just formatted to conform to the specification
=> [optimize]opt code format

.github/workflows/ci.yml, Makefile
Ensure there is no unused dependency being added by accident and all generated code is committed, just like in flow-go https://github.com/onflow/flow-go/blob/master/Makefile#L125-L132
=> Check tidy

go.mod, go.sum
See:
- https://github.com/onflow/cadence/releases/tag/v0.11.0
- https://github.com/onflow/cadence/releases/tag/v0.11.1
- https://github.com/onflow/cadence/releases/tag/v0.11.2
=> Update to Cadence v0.11.2

crypto/cloudkms/cloudkms.go, go.mod
Allow for configuring google KMS client with options object.
=> Allow passing options to KMS client constructor.

README.md, README_zh_CN.md
Fixes: #121 
This PR fixes broken links in both the English and Chinese READMEs.
cc @Randy1Burrell
______
=> Fix broken links in README

crypto/internal/crypto/hash/hash_test.go, crypto/internal/crypto/hash/kmac.go, go.mod, go.sum, test/entities.go
Work towards onflow/flow#309
______
=> Update to Cadence v0.12.1

docs/index.mdx
Adding this folder for pulling markdown docs content directly into Gatsby site.
=> Add docs folder.

templates/accounts.go
In order to fix https://github.com/onflow/flow-cli/pull/69/
=> added template to remove contract with a given name

go.mod, go.sum
Update to [Cadence v0.13.0](https://github.com/onflow/cadence/releases/tag/v0.13.0)
______
=> Update to Cadence v0.13.0

address.go, address_test.go
- Fix order of arguments passed to TrimPrefix
- Handle uneven input length
______
=> Fix HexToString

.github/workflows/ci.yml
=> Run CI for PRs

transaction.go
Refresh signer index on `Add` and not just `Set` for signatures
______
=> Refresh signer index

address_test.go
Also test leading zeros are properly handled
---
=> Extend the hex-to-address tests

go.mod, go.sum
Release notes:
- [V0.13.7](https://github.com/onflow/cadence/releases/tag/v0.13.7)
- [V0.13.8](https://github.com/onflow/cadence/releases/tag/v0.13.8)
- [V0.14.0](https://github.com/onflow/cadence/releases/tag/v0.14.0)
- [V0.14.1](https://github.com/onflow/cadence/releases/tag/v0.14.1)
- [V0.14.2](https://github.com/onflow/cadence/releases/tag/v0.14.2)
______
=> Update to Cadence v0.14.2

examples/examples.go, examples/flow.json
Fix for [the latest Flow CLI Configuration format.](https://docs.onflow.org/flow-cli/configuration)
- Issues
- https://github.com/onflow/flow-go-sdk/issues/187
- https://github.com/onflow/flow-go-sdk/issues/188
______
=> Fix example

account.go, account_test.go
Implement validation of account key weights.
______
=> Validate Account Key Weight

examples/examples.go, examples/user_signature/main.go, templates/accounts.go
Closes: https://github.com/onflow/flow-emulator/issues/60
Fix the sdk examples to work with emulator version in this PR: https://github.com/onflow/flow-emulator/pull/61
______
=> Fix examples to work with the new emuator version

docs/generating-keys.mdx
- Update to correct link for supported signature hash algos
=> Update Generating Keys - deadlink

docs/sending-transactions.mdx, docs/signing-transactions.mdx
=> Docs updates

docs/index.mdx
Closes: None
Update reference to use `self.guest` correctly
______
=> Update reference to use `self.guest` correctly

docs/index.mdx
Small documentation update fixing broken links.
=> Remove broken links

examples/transaction_signing/multi_party_two_authorizers/main.go
Small bug fix in the script source code.
______
=> Bugfix: bug in example script

go.mod, go.sum
Update flow-go/crypto to the latest release
=> Update the crypto version

crypto/cloudkms/signer.go
Closes: #260 
Create a new `hasher` in cloudkms signer, when signing flow transactions.
______
=> Fix cloudkms signer is not threadsafe

account_proof.go, account_proof_test.go
Closes: #???
- Update the account proof encoding function
______
=> Add updated account proof encoding function

docs/index.mdx
=> Update broken link

client/convert/protobuf.go, test/entities.go, transaction.go
Closes: #???
Added `BlockID` to `TransactionResult`
______
=> add blockID in transaction result

go.mod, go.sum
Update to [Cadence v0.24.1](https://github.com/onflow/cadence/releases/tag/v0.24.1)
______
=> Update to Cadence v0.24.1

go.mod, go.sum
https://github.com/onflow/cadence/releases/tag/v0.24.3
______
=> Update Cadence v0.24.3

go.mod, go.sum
https://github.com/onflow/cadence/releases/tag/v0.24.6
______
=> Upgrade cadence to v0.24.6

go.mod, go.sum
- [onflow/cadence v0.28.0](https://github.com/onflow/cadence/releases/tag/v0.28.0)
=> Auto update to onflow/cadence v0.28.0

docs/index.mdx
Closes: #330
This corrects an inaccuracy in the documentation relating to the transaction status.
______
=> #330 - Update documentation

access/client.go, access/grpc/client.go, access/grpc/convert.go, access/grpc/grpc.go, access/grpc/grpc_test.go, access/http/client.go, transaction.go
=> Add GetTransactionsByBlockID and GetTransactionResultsByBlockID

go.mod, go.sum
- [onflow/cadence v0.31.2](https://github.com/onflow/cadence/releases/tag/v0.31.2)
=> Auto update to onflow/cadence v0.31.2

go.mod, go.sum
- [onflow/cadence v0.31.3](https://github.com/onflow/cadence/releases/tag/v0.31.3)
=> Update to Cadence v0.31.3

docs/index.mdx
=> Fix wrong import

go.mod, go.sum
- [onflow/cadence v0.34.0](https://github.com/onflow/cadence/releases/tag/v0.34.0)
=> Auto update to onflow/cadence v0.34.0

docs/error-codes.mdx, docs/flow-docs.json
Add Error Codes description file
______
=> add error codes doc and flow-docs json file

access/grpc/convert_test.go, access/grpc/grpc_test.go, go.mod, go.sum
- [onflow/cadence v0.35.0](https://github.com/onflow/cadence/releases/tag/v0.35.0)
=> Update Cadence to v0.35.0

go.mod, go.sum
- [onflow/cadence v0.39.2](https://github.com/onflow/cadence/releases/tag/v0.39.2)
=> Auto update to onflow/cadence v0.39.2

go.mod, go.sum
- [onflow/cadence v0.39.14](https://github.com/onflow/cadence/releases/tag/v0.39.14)
=> Auto update to onflow/cadence v0.39.14

go.mod, go.sum
- [onflow/cadence v0.40.0](https://github.com/onflow/cadence/releases/tag/v0.40.0)
=> Auto update to onflow/cadence v0.40.0

go.mod, go.sum
=> Update cadence version to v0.41.0-stable-cadence.1

address.go, flow.go
=> Remove sandboxnet

README.md
Closes: #469 
Update `README.md` with additional information about ANs.
______
=> Add AN Section to README.md

go.mod, go.sum
=> [v0.41] Update to Cadence v0.42.1

go.mod, go.sum
=> Update to Cadence v0.42.3

.github/workflows/ci.yml, go.mod, go.sum
=> Upgrade cadence

go.mod, go.sum
=> Update to Cadence v1.0.0-M3

go.mod, go.sum
- [onflow/cadence v1.0.0-M7](https://github.com/onflow/cadence/releases/tag/v1.0.0-M7)
=> Update to Cadence v1.0.0-M7

access/grpc/client.go, access/http/client.go, flow.go
Part of effort to rename crescendo to previewnet in our tools.
=> Switch Crescendo to Previewnet

access/grpc/client.go
Cherry picks this PR from the `v0.41` branch: https://github.com/onflow/flow-go-sdk/pull/578
______
=> Cherry pick WaitServer

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.10](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.10)
=> Update to Cadence v1.0.0-preview.10

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.12](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.12)
=> Update to Cadence v1.0.0-preview.12

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.13](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.13)
=> Update to Cadence v1.0.0-preview.13

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.14](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.14)
=> Update to Cadence v1.0.0-preview.14

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.15](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.15)
=> Update to Cadence v1.0.0-preview.15

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.16](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.16)
=> Update to Cadence v1.0.0-preview.16

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.19](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.19)
=> Update to Cadence v1.0.0-preview.19

go.mod, go.sum
=> Update v0 to Cadence v0.42.10

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.20](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.20)
=> Update to Cadence v1.0.0-preview.20

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.22](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.22)
=> Update to Cadence v1.0.0-preview.22

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.23](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.23)
=> Update to Cadence v1.0.0-preview.23

access/http/convert_test.go, event.go, go.mod, go.sum
- [onflow/cadence v1.0.0-preview.24](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.24)
=> Update to Cadence v1.0.0-preview.24

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.30](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.30)
=> Update to Cadence v1.0.0-preview.30

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.31](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.31)
=> Update to Cadence v1.0.0-preview.31

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.32](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.32)
=> Update to Cadence v1.0.0-preview.32

go.mod, go.sum
Depends on #679 
- [onflow/cadence v1.0.0-preview.33](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.33)
=> Update to Cadence v1.0.0-preview.33

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.34](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.34)
=> Update to Cadence v1.0.0-preview.34

examples/go.mod, examples/go.sum, go.mod, go.sum, templates/accounts.go, test/entities.go
- [onflow/cadence v1.0.0-preview.35](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.35)
=> Update to Cadence v1.0.0-preview.35

address.go, address_test.go
Closes: https://github.com/onflow/flow-go-sdk/issues/700
Added code word to support address generation on Previewnet
______
=> add Previewnet codeword for address generation

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.37](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.37)
=> Update to Cadence v1.0.0-preview.37

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.39](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.39)
=> Update to Cadence v1.0.0-preview.39

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.40](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.40)
=> Update to Cadence v1.0.0-preview.40

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.42](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.42)
=> Update to Cadence v1.0.0-preview.42

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.43](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.43)
=> Update to Cadence v1.0.0-preview.43

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.44](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.44)
=> Update to Cadence v1.0.0-preview.44

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.50](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.50)
=> Update to Cadence v1.0.0-preview.50

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.51](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.51)
=> Update to Cadence v1.0.0-preview.51

go.mod, go.sum
- [onflow/cadence v1.0.0-preview.52](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.52)
=> Update to Cadence v1.0.0-preview.52

go.mod, go.sum
- [onflow/cadence v1.0.0](https://github.com/onflow/cadence/releases/tag/v1.0.0)
=> Update to Cadence v1.0.0

decode.go, decode_test.go, event.go, examples/examples.go, examples/go.mod, examples/go.sum, go.mod, go.sum, templates/accounts.go, test/entities.go
- [onflow/cadence v1.1.0](https://github.com/onflow/cadence/releases/tag/v1.1.0)
=> Update to Cadence v1.1.0

go.mod, go.sum
- [onflow/cadence v1.2.1](https://github.com/onflow/cadence/releases/tag/v1.2.1)
=> Update to Cadence v1.2.1

go.mod, go.sum
- [onflow/cadence v1.3.0](https://github.com/onflow/cadence/releases/tag/v1.3.0)
=> Update to Cadence v1.3.0

go.mod, go.sum
- [onflow/cadence v1.3.3](https://github.com/onflow/cadence/releases/tag/v1.3.3)
=> Update to Cadence v1.3.3

go.mod, go.sum
- [onflow/cadence v1.6.3](https://github.com/onflow/cadence/releases/tag/v1.6.3)
=> Update to Cadence v1.6.3

go.mod, go.sum
- [onflow/cadence v1.7.1](https://github.com/onflow/cadence/releases/tag/v1.7.1)
=> Update to Cadence v1.7.1
