- .github/workflows/ci.yml
- Makefile
GH Actions do not have permissions to pull our private go dependencies, so this will fail until we publish the `flow` and `cadence` repos.
> Enable GitHub Action for CI

- client/convert/protobuf.go
- client/convert/protobuf_test.go
Ref: https://github.com/dapperlabs/flow-emulator/issues/46
Account key IDs were being omitted from protobuf messages. This PR fixes the `convert` package to include them.
> Include account key IDs in protobuf messages

- client/client_test.go
- client/convert/protobuf.go
- client/convert/protobuf_test.go
This PR cleans up and refactors unit tests for the `client` package.
- Add `clientTest` helper to consolidate common test setup
- Replace `assert` with `require` in cases where test will halt if error occurs
- Add test cases for `Ping`, `GetAccount` and `ExecuteScriptAtLatestBlock`
> Client: Clean up unit tests

- client/client.go
- client/client_test.go
- client/convert/protobuf.go
- client/convert/protobuf_test.go
⚠️ Depends on #25 
This PR implements the remaining `ExecuteScript` methods on the `client.Client` struct.
- Implement `ExecuteScriptAtBlockID`
- Implement `ExecuteScriptAtBlockHeight`
- Add `convert.CadenceValueToMessage` and `convert.MessageToCadenceValue` functions
> Client: Add ExecuteScriptAtBlockID, ExecuteScriptAtBlockHeight

- Makefile
- client/client.go
- client/convert/protobuf.go
- client/convert/protobuf_test.go
- test/entities.go
Depends on #26
This PR cleans up the unit tests for the `client/convert` package.
- Sort all `convert` functions alphabetically
- Sort all `test` generators alphabetically
- Add test cases for:
- `AccountToMessage`, `MessageToAccount`
- `BlockHeaderToMessage`, `MessageToBlockHeader`
- `CollectionGuaranteeToMessage`, `MessageToCollectionGuarantee`
- `CollectionGuaranteesToMessages`, `MessagesToCollectionGuarantees`
- `IdentifierToMessage`, `MessageToIdentifier`
- `IdentifiersToMessages`, `MessagesToIdentifiers`
- Add `coverage` target to Makefile that displays test coverage stats
> Client: Convert test cleanup

- go.mod
- go.sum
Bump `onflow/cadence` version to `v0.3.0-beta1`.
> Upgrade Cadence to v0.3.0-beta1

- templates/accounts.go
- templates/accounts_test.go
This PR updates `templates.CreateAccount` to use the new `AuthAccount` constructor introduced by https://github.com/onflow/cadence/pull/138.
> Update templates.CreateAccount to use new AuthAccount constructor

- README.md
- address.go
- address_test.go
- client/client_test.go
- crypto/crypto.go
- examples/create_account/main.go
- examples/deploy_contract/main.go
- examples/examples.go
- examples/flow.json
- flow.go
- go.mod
- go.sum
- test/entities.go
- transaction.go
- transaction_test.go
This PR integrates the new account addressing mechanism. 
- integrate three addressing mechanisms (mainnet, testnet and emulator).
- rename `Root` account to `Service` account.
- new values for `ZeroAddress` and `ServiceAddress`.
- provide an off-chain method to check addresses validity.
> Update the account address generation

- go.mod
- go.sum
This PR updates the SDK to use the latest Cadence release: https://github.com/onflow/cadence/releases/tag/v0.4.0-beta1
> Upgrade Cadence to v0.4.0-beta1

- client/convert/protobuf.go
- client/convert/protobuf_test.go
- test/entities.go
Closes #46
This updates the `Block` and `BlockHeader` client methods to be compatible with versions of the Access API that do no implement the `BlockHeader.Timestamp` field.
> client/convert: Skip decoding of block timestamp if nil

- examples/examples.go
- examples/flow.json
This PR introduces a small improvement to the `examples` package that loads the service account information from `flow.json` rather than a hard-coded seed.
> Update emulator examples to read service key from flow.json

- README.md
- crypto/crypto.go
- clarify why `InMemorySigner` is considered not secure (it is not simply because the key is in memory).
- minor comment update
> Update crypto comments

- collection.go
- event.go
- flow.go
- transaction.go
Closes: #54
This PR introduces a thread-safe hasher that can be used to safely compute IDs for Flow entities from multiple routines.
> Add thread-safe entityHasher

- crypto/crypto.go
This enum is no longer being used can be removed from the `crypto` package.
We may revisit this API in the future and reintroduce a similar concept.
> crypto: Remove KeyType enum

- client/client.go
- client/client_test.go
- client/errors.go
Closes: #32 
This PR improves the error values returned by a `client.Client` instance. 
gRPC errors are wrapped in a `client.RPCError` type that can be used as follows:
```go
import "google.golang.org/grpc/status"
res, err := c.GetTransactionResult(...)
if err != nil {
s, ok := status.FromError(err)
...
}
```
> client: Add dedicated error types for RPC and conversion errors

- client/convert/protobuf.go
- client/convert/protobuf_test.go
- examples/transaction_arguments/main.go
- test/entities.go
- transaction.go
- transaction_test.go
Closes: #66 
This PR introduces a change to the way transaction arguments are stored on the `flow.Transaction` data type.
Because the _encoded_ arguments are used to determine the transaction hash, they must stay consistent across different representations of the same transaction. For example, when decoding a transaction from protobuf, we need to ensure that the original argument encoding is preserved in order to generate the same transaction hash.
Previously the `flow.Transaction` type was not lossless with regards to transaction arguments; by choosing to store arguments as `cadence.Value` types, we forced users of `flow.Transaction` to lose the original encoding (i.e. changes in JSON whitespace, indentation, etc).
This PR updates `flow.Transaction` to store arguments as raw bytes. 
- …
> Add RawArgument and Argument functions to flow.Transaction

- client/client.go
- client/client_test.go
- client/mock_client_test.go
- go.mod
- go.sum
Closes: #63 63
Access API method `GetAccount` has been renamed to `GetAccountAtLatestBlock`. This change is for updating `flow-go-sdk` to the latest Access Node API.
______
> Rename GetAccount to GetAccountAtLatestBlock

- examples/user_signature/main.go
- go.sum
This PR updates the `user_signature` example to reconstruct the signed message using the newly added `toBytes` and `toBigEndianBytes` functions.
> Update user signature example to encode values

- transaction.go
Expiry string was not added in the String() method of `TransactionStatus` and causes printing of `TransactionStatusExpired` to panic.
______
> add expiry transaction status

- README.md
- examples/Makefile
- examples/README.md
- examples/transaction_signing/multi_party/main.go
- examples/transaction_signing/multi_party_two_authorizers/main.go
I did not make an issue for this should I do that?
There are no examples on how to get two authorisers in a transaction. This fixes that
______
> added example that uses 2 authorisers

- templates/accounts.go
This fixes an inefficiency in the account creation template that was causing a the `setCode` method to always be called, even if there is no code to deploy.
> templates: Do not deploy empty code string on account creation

- client/client.go
- client/client_test.go
- go.mod
- go.sum
Closes: #99
Added BlockTimestamp to the access node EventsResponse. This allows you to know when the event was published without re-requesting the block by block id.
> Added BlockTimestamp to BlockEvents response

- README.md
- account.go
- client/convert/protobuf.go
- examples/add_account_key/main.go
- examples/create_account/main.go
- examples/deploy_contract/main.go
- examples/examples.go
- examples/query_events/main.go
- examples/transaction_arguments/main.go
- examples/transaction_signing/multi_party/main.go
- examples/transaction_signing/multi_party_multisig/main.go
- examples/transaction_signing/multi_party_two_authorizers/main.go
- examples/transaction_signing/single_party/main.go
- examples/transaction_signing/single_party_multisig/main.go
- templates/accounts.go
- test/entities.go
- transaction.go
- transaction_test.go
This PR updates the definition for `flow.AccountKey` based on recent protocol changes.
- Add `Revoked` flag that indicates if a key has been revoked from an account
- Rename `AccountKey.ID` to `AccountKey.Index`
> Update flow.AccountKey to match latest protocol changes

- .github/workflows/ci.yml
- examples/add_account_key/main.go
- examples/create_account/main.go
- examples/deploy_contract/main.go
- examples/examples.go
- examples/query_events/main.go
- examples/transaction_arguments/main.go
- examples/transaction_signing/multi_party/main.go
- examples/transaction_signing/multi_party_multisig/main.go
- examples/transaction_signing/multi_party_two_authorizers/main.go
- examples/transaction_signing/single_party/main.go
- examples/transaction_signing/single_party_multisig/main.go
- go.mod
- go.sum
SDK examples didn't set ReferenceBlockId which has become mandatory. Emulator was updated to also require this: https://github.com/dapperlabs/flow-emulator/pull/103
> Updated sdk examples

- go.mod
- go.sum
There was [a regression in v0.10.0](https://github.com/onflow/cadence/issues/445). 
Update to v0.10.1 which [fixes it](https://github.com/onflow/cadence/pull/446).
> Update Cadence to v0.10.1

- examples/user_signature/main.go
- templates/accounts.go
- templates/accounts_test.go
ref: https://github.com/dapperlabs/flow-go/issues/5056
Using `[Uint8]` parameter type to pass contract code to a transaction was causing the transaction size to grow with 30 bytes per byte of contract code. 
This was because converting a byte array to a cadence Uint array wrapped every byte with a lot extra type data.
I circumvented this by passing the code to the transaction as a hex encoded string instead of a `[Uint8]`. Doing it this way every byte of contract code increases the transaction size by only 2 bytes (because of the hex encoding).
A possible future expansion would be to use base64 encoding which would have a ratio of 1.3. Or even better than that, some sort of compression.
This was tested with this emulator version https://github.com/onflow/flow-emulator/tree/bastian/update-s …
> Fix transaction size growing very quickly

- go.mod
- go.sum
Update to [Cadence v0.10.2](https://github.com/onflow/cadence/releases/tag/v0.10.2), which contains an important fix for backwards-compatibility
> Update to Cadence v0.10.2

- client/client.go
Fixes: #125
This PR adds the `...grpc.CallOption` parameter to all Access API gRPC client functions on `client.Client`, allowing the caller to configure the functionality of the underlying gRPC client.
cc @yndc
______
> Add call options parameter to all Access API gRPC client functions

- flow.go
- go.sum
- transaction.go
- transaction_test.go
Closes: #115
Adds RLP decode functionality for transactions
Two main considerations here:
- Is this how we want to handle the canonical forms? I've pulled them out as private structs, but not sure if this is the desired implementation
- Why does the transaction signature have address, but not pass it along? This causes all of my envelope decode tests to fail
______
> Add transaction decoding

- client/client.go
- client/client_test.go
Closes: #
Adds the GetAccountAtBlockHeight client function, corresponding to: https://github.com/onflow/flow/blob/master/protobuf/flow/access/access.proto#L62 rpc
______
> Add GetAccountAtBlockHeight

- examples/Makefile
- examples/deploy_contract/main.go
- examples/storage_usage/main.go
Closes: https://github.com/dapperlabs/flow-internal/issues/1369
Added an example for storage:
- transaction tries to store a large resource
- demonstrates that acct.storageUsed will change after adding resource
- demonstrates that acct.storageUsed can be compared to acct.stroageCapacity
- demonstrates the the error for going over limit is predictable
______
> Storage fees and account minimum balance example

- decode.go
- decode_test.go
- event.go
Closes onflow/cadence#509
______
> Fix the decoding of Flow type IDs by importing Cadence's type ID decoder

- go.mod
- go.sum
Update to the latest release of Cadence, [v0.12.6](https://github.com/onflow/cadence/releases/tag/v0.12.6)
______
> Update to Cadence v0.12.6

- client/client.go
- client/client_test.go
- client/mock_client_test.go
- go.mod
- go.sum
Toward: https://github.com/dapperlabs/flow-go/issues/4899
Adds a method to `sdk.Client` for retrieving the latest protocol state snapshot (corresponding to the API added on the Access node in https://github.com/onflow/flow-go/pull/377). This will be used by Flow nodes joining the network at an epoch boundary (as opposed to during a spork) to bootstrap a space-efficient local protocol state from an arbitrary state snapshot (see https://github.com/onflow/flow-go/pull/209).
______
> Add client method for getting latest protocol state snapshot

- examples/deploy_contract/main.go
- examples/examples.go
- examples/flow.json
- examples/storage_usage/main.go
- examples/transaction_signing/multi_party/main.go
- examples/transaction_signing/multi_party_multisig/main.go
- examples/transaction_signing/multi_party_two_authorizers/main.go
- examples/transaction_signing/single_party/main.go
- examples/transaction_signing/single_party_multisig/main.go
ref: https://github.com/dapperlabs/flow-internal/issues/1384
The goal was to change the examples to work with transaction fees turned on.
This is just a suggestion.
How it works is that I added a `fund account` to the examples, which adds some flow to an account. Adding that little bit of flow in the examples makes them work even if the transaction fees or on.
This works with this version of the emulator: https://github.com/onflow/flow-emulator/pull/28 and transaction fees turned on.
Some questions I have:
- is this a good approach?
- where should I put the mint tokens script?
- how do I put the default flow addresses in the json? (I know this kid of connects to https://github.com/onflow/flow-cli/issues/30)
______
> Update examples to work with tx fees

- docs/creating-accounts.mdx
The [rename commit](https://github.com/yihau/flow-go-sdk/commit/96796f0cabc1847d7879a5230ab55fd3cdd41ae8) seems not update the docs together. I update docs/creating-accounts.mdx to correspond to the current AccountKey struct in golang.
> fix outdated info in docs/creating-accounts.mdx

- block.go
- client/convert/protobuf.go
- client/convert/protobuf_test.go
- test/entities.go
Closes: #148
Implements the `Seals` property of `BlockPayload` using the technique used for `CollectionGuarantees` as a guide.
Some [context on Discord](https://discord.com/channels/613813861610684416/709804784089301002/810364494902591488).
______
> Add Seals to BlockPayload

- address.go
- address_test.go
Closes: #151 
Remove the 0x prefix if it exist from the string before parsing
> remove 0x prefix from string if sent to HexToAddress

- transaction.go
- transaction_test.go
Closes: #163 
The `compareSignatures` function was not sorting correctly on two values.
______
> Fix incorrect transaction signature ordering

- event.go
> updated copyright year and added new event types

- go.mod
- go.sum
Work towards dapperlabs/flow-go#5372
Update to Cadence v0.13.5. Release notes:
- [v0.13.1](https://github.com/onflow/cadence/releases/tag/v0.13.1)
- [v0.13.2](https://github.com/onflow/cadence/releases/tag/v0.13.2)
- [v0.13.3](https://github.com/onflow/cadence/releases/tag/v0.13.3)
- [v0.13.4](https://github.com/onflow/cadence/releases/tag/v0.13.4)
- [v0.13.5](https://github.com/onflow/cadence/releases/tag/v0.13.5)
______
> Update to Cadence v0.13.5

- go.mod
- go.sum
This update includes an important bugfix: https://github.com/onflow/cadence/releases/tag/v0.13.6
______
> Update to Cadence v0.13.6

- crypto/crypto.go
- crypto/crypto_test.go
Closes: N/A
Was running into a PEM decode issue when working with some KMS keys. Kept getting `cryptokms: failed to parse PEM public key: input has incorrect ECDSA_P256 key size`.
The cause of this is sometimes, when calling `.Bytes()` on the X and Y points after decoding the PEM key, the corresponding byte slices were not the full 32 bytes, which was expected by the next function (expecting ECDSA_P256 keys to have a raw key of length 64)
This adds left padding (since the bytes are returned big endian) up to the expected length for ECDSA_P256 only. Can add other known lengths as we start to use them more.
______
> Fix PEM decoding issue for some KMS keys

- crypto/cloudkms/cloudkms.go
- crypto/crypto.go
- crypto/crypto_test.go
This PR doesn't address any ticket.
- simplifies the private and public key structures by using the `flow-go/crypto` structures.
- cleans up redundant functions.
> [Crypto] Simplify nested key structures

- docs/building-transactions.mdx
- docs/creating-accounts.mdx
- docs/generating-keys.mdx
- docs/index.mdx
- docs/querying-accounts.mdx
- docs/querying-blocks.mdx
- docs/querying-events.mdx
- docs/querying-transactions.mdx
- docs/sending-transactions.mdx
- docs/signing-transactions.mdx
- docs/transfer-flow.mdx
Possible content types: 
`HOWTO` (Guide)
`TUT` (Tutorial)
`INTRO` (index /intro page)
`EXP` (Explainer)
`REF` (Reference)
`FAQ` (Answers)
* all `README` are considered `INTRO` and all `CHANGELOG`&`WARNING` are considered `REF`
As outlined here: https://www.notion.so/dapperlabs/Types-of-Docs-033e722018f34036811ff38dac03eded
PR also formats whitespace.
> Adds contentType tags.

- crypto/crypto.go
- crypto/crypto_test.go
- go.mod
Closes: #176
- refactor `DecodePublicKeyPEM` to optimize an extra round of decoding and encoding.
- add support for ECDSA keys for secp256k1.
- improve the tests.
> [Crypto] DecodePublicKeyPEM supports ECDSA secp256k1 keys 

- crypto/cloudkms/cloudkms.go
The Google KMS gRPC API does not yet have first class support for the secp256k1 signature algorithm.
This PR implements a workaround that we should replace once the API is updated. It's not ideal, but it will be backwards compatible once Google rolls out proper support in the API.
______
> Add support for Google KMS keys with secp256k1 algorithm

- crypto/cloudkms/signer.go
- examples/cloudkms/main.go
Remove unused address from Signer KMS implementation.
Method `SignerForKey` requires an address that might not even exist and I don't think it has an usecase. 
Example usage: https://github.com/onflow/flow-cli/blob/master/pkg/flowcli/project/keys.go#L117
> Remove unused address

- transaction.go
Due to https://github.com/onflow/flow-go/pull/1220 a gas limit of 0 is no longer a valid gas limit.
I changed the default gas limit (when you call `NewTransaction()` to 1000, which is enough for all of the examples.
Any comments on the default gas limit amount are very welcome. 
This relates to this emulator PR https://github.com/onflow/flow-emulator/pull/78.
______
> Add non-zero default transaction gas limit

- README.md
- README_zh_CN.md
- docs/index.mdx
Some documents are using 0.1 and 1.0 as key weight, which should be in the range of [1, 1000].
This change help with issue https://github.com/onflow/flow/issues/473
______
> correct key weight document to be in the range of [1, 1000]

- account_proof.go
- account_proof_test.go
- sign.go
Closes: #245
Added helper functions for generating account proof messages for signing.
______
> Add account proof helpers

- examples/storage_usage/main.go
I noticed that one of the examples doesn't work when working on https://github.com/onflow/flow-emulator/pull/127. I checked and it also doesn't work on the current version of the emulator.
I'm not sure when it stopped working, but I assume its when we made failing transactions also use up a sequence number, which was a while ago.
______
> Fix storage used example

- crypto/cloudkms/cloudkms.go
Closes: #194
Closes: #201 
This PR makes the `cloudkms` algo parsing functions exported and adds a `KMSClient()` method for accessing the `KeyManagementClient` directly (e.g. for closing the client as requested in #194). Original PR #204, this PR contains the suggested modifications.
______
> Export cloudkms algorithm parsing functions and add method for accessing KeyManagementClient

- templates/accounts.go
Adding the account key didn't use the new templates. This has been fixed.
______
> Fix adding account key

- CODEOWNERS
The crypto package of `flow-go-sdk` is based on the crypto package from `flow-go`. This PR adds the code owner of `flow-go/crypto`  (@tarakby) as a code owner to `flow-go-sdk/crypto` to make sure he is notified for future updates, in order to review the changes and help maintaining the package.
The crypto package still remains owned by the code owners of the `flow-go-sdk` repo.
______
> Add new code owner for the crypto package

- examples/add_account_key/main.go
- examples/create_account/main.go
- examples/deploy_contract/main.go
- examples/examples.go
- examples/modify_account/main.go
- templates/accounts.go
- templates/accounts_test.go
Made AccountKeyToCadenceCryptoKey public so it can be used elsewhere as it is a very useful way to encode keys.
Changed newHashAlgoValue and  newSignAlgoValue because newHashAlgoValue was not able to encode some hash algos correclty.
______
> Add account key changes

- .github/workflows/call-refresh-doc.yml
Closes [#67](https://github.com/onflow/next-docs-v1/issues/67)
Create Github Actions in Documentation Sources, aka github repositories:
There are 2 workflows: 1. call-refresh-doc, 2. refresh-doc. First parses the documentation for diffs, and calls the second if there are any.
This repo only has the first workflow, and will call the refresh-doc workflow in /flow https://github.com/onflow/flow/pull/953
Used tj-actions/changed-files@v18.7 to get all the doc files that were edited
Logs more detailed information (added, deleted, modified) for the diff files
Calls the doc site's refresh endpoint located in /flow with the content paths, SHA, and repository name
______
> Add github actions for getting diff & calling refresh

- access/grpc/convert.go
- access/grpc/convert_test.go
- access/grpc/grpc.go
- access/http/client_test.go
- access/http/convert.go
- access/http/convert_test.go
- access/http/http.go
- go.mod
- go.sum
- transaction.go
https://github.com/onflow/cadence/pull/1733  added support for decoding Cadence JSON values that were encoded using the previous format. 
Update to Cadence v0.24.4 which contains this feature, and add support for allowing users of the SDK to pass JSON options. 
By adding the options to the client, all the `Client` functions can stay as-is.
______
> Update to Cadence v0.24.4, allow passing JSON options

- event.go
Closes: #???
Fixed `EventAccountAdded` event type to `EventAccountKeyAdded`
______
> Fix EventAccountKeyAdded

- access/http/convert.go
- access/http/fixtures_test.go
Closes: #???
Added `BlockID` to `TransactionResult` in a return value of the convert function.
> Fix toTransactionResult to include blockID

- access/http/handler.go
- access/http/handler_test.go
Closes: #???
Fixed HTTP post error response message to be included in the error returned by the handler. 
HTTP post has been returning empty error message like below.
```go
http.HTTPError{
Url:     "http://127.0.0.1:8888/v1/transactions",
Code:    0,
Message: "",
}
```
______
> Fix access http post error response

- access/grpc/grpc.go
- access/http/http.go
Closes: https://github.com/onflow/flow-cli/issues/543
By default add the cadence JSON parsing option to allow pre-fork formats.
______
> Allow Cadence Unstructured Static Types

- access/grpc/convert.go
- go.mod
- go.sum
- test/entities.go
- transaction.go
Closes: #307 
Add missing BlockHeight to the TransactionResult.  Note that this update is only for the GRPC API call and does not update the HTTP endpoint.  Comments in issue refer requiring openapi schema needing updates so new models can be generated, out of scope for this PR.
______
> Add BlockHeight to TransactionResult

- docs/index.mdx
Closes: [onflow/next-docs-v1#](https://github.com/onflow/next-docs-v1/issues/528)
The `style` tag here is causing this file to fail to compile on the new docs site because JSX requires `style`s to be an object mapping and not raw strings. I removed the style attribute entirely because it seems mostly unnecessary? But I'm not 100% sure if it's needed for some other reason, so I am happy add it back using `style={{ margin: 0 }}` if preferred!
______
> Update index.mdx to remove invalid style tag

- crypto/cloudkms/cloudkms_test.go
- crypto/cloudkms/signer.go
Closes: https://github.com/onflow/flow-go-sdk/issues/317
Fixes a bug when messages signed by Google KMS are longer than 65536 bytes. 
If the message is longer than the KMS limit, pre-hash the message outside KMS. 
______
> [Crypto] fix KMS signing bug for long messages

- address.go
- flow.go
Address generator on flow-go supports more type of networks, updating the files here to match the one on the flow-go, 
If won't impact previously existed network names here just support more networks like benchnet. 
______
> Update address generator to match the flow-go

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
I'd love to review all issues, but probably best that somebody else is tagged on these since I'm no longer the primary maintainer!
> Remove psiemens as default issue assignee

- access/http/client.go
It was preventing the http client to work.
Closes: #???
______
> remove '/' from the end of the rest access URI

- address.go
- flow.go
Closes: #327 
Adds flow-sandboxnet as a valide chain ID, to match flow-go.
mostly a re-name, from stagingnet to sandboxnet
______
> Add sandboxnet ID

- go.mod
- go.sum
- [onflow/cadence v0.38.0](https://github.com/onflow/cadence/releases/tag/v0.38.0)
> Auto update to onflow/cadence v0.38.0

- go.mod
- go.sum
- [onflow/cadence v0.39.5](https://github.com/onflow/cadence/releases/tag/v0.39.5)
> Auto update to onflow/cadence v0.39.5

- go.mod
- go.sum
- [onflow/cadence v0.39.6](https://github.com/onflow/cadence/releases/tag/v0.39.6)
> Auto update to onflow/cadence v0.39.6

- go.mod
- go.sum
- [onflow/cadence v0.39.8](https://github.com/onflow/cadence/releases/tag/v0.39.8)
> Auto update to onflow/cadence v0.39.8

- go.mod
- go.sum
- [onflow/cadence v0.39.12](https://github.com/onflow/cadence/releases/tag/v0.39.12)
> Auto update to onflow/cadence v0.39.12

- .github/workflows/ci.yml
We might need to maintain versioned branches. e.g: https://github.com/onflow/flow-go-sdk/pull/425
So enabling CI for those branches as well.
______
> Enable CI for versioned branches

- access/grpc/convert.go
- test/entities.go
- transaction.go
Transaction results include a `CollectionID` field which indicates which collection the transaction was included in. See protobuf:
https://github.com/onflow/flow/blob/3f149a861ec42550915e63d188e4328d5ee38445/protobuf/flow/access/access.proto#L249-L259
This PR adds the `CollectionID` field to the response for endpoints returning `TransactionResult` objects.
______
> Add support for CollectionID in TransactionResult

- go.mod
- go.sum
Port #438 to v0.41, because master cannot be used in flow-go yet.
______
> [v0.41] Update to Cadence v0.40.0

- go.mod
- go.sum
- [onflow/cadence v0.41.1](https://github.com/onflow/cadence/releases/tag/v0.41.1)
> Auto update to onflow/cadence v0.41.1

- go.mod
- go.sum
Update cadence to [v0.42.4](https://github.com/onflow/cadence/releases/tag/v0.42.4)
______
> Update cadence to v0.42.4

- access/grpc/convert.go
- access/grpc/convert_test.go
- access/grpc/grpc.go
- go.mod
- go.sum
- test/entities.go
Closes: https://github.com/onflow/flow-go-sdk/issues/500
The AccessAPI recently added support for specifying the encoding for events returned in the request. CCF encoding is significantly more compact and includes additional information that can't be included in JSON-CDC format.
This PR updates all gRPC calls to endpoints that support CCF encoding to use the new format, and handles conversion to the original cadence object. The change should be transparent to the caller, except that less data is transported over the web.
______
> Use CCF encoding when requesting events from AccessAPI

- go.mod
- go.sum
Update cadence to [v0.42.5](https://github.com/onflow/cadence/releases/tag/v0.42.5)
______
> Update cadence to v0.42.5

- go.mod
- go.sum
Update cadence to [v0.42.6](https://github.com/onflow/cadence/releases/tag/v0.42.6)
______
> Update cadence to v0.42.6

- address.go
- address_test.go
Closes: https://github.com/onflow/flow-go-sdk/issues/553
Add HexWithPrefix method so user's don't have to prepend "0x" to addresses and added unit tests.
______
> add convenience method for getting prefixed address as string

- go.mod
- go.sum
Updating to cadence https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.2
______
> Update to newest Cadence 1.0 preview

- access/grpc/client.go
- access/http/client.go
- flow.go
Issue: #559 
- Add Crescendo ChainID for use by other packages
- Add Crescendo host constants for grpc and http
______
> add Crescendo Support

- go.mod
- go.sum
- [onflow/cadence v1.0.0-M5](https://github.com/onflow/cadence/releases/tag/v1.0.0-M5)
> Update to Cadence v1.0.0-M5

- go.mod
- go.sum
- [onflow/cadence v1.0.0-M6](https://github.com/onflow/cadence/releases/tag/v1.0.0-M6)
> Update to Cadence v1.0.0-M6

- go.mod
- go.sum
- [onflow/cadence v1.0.0-M8](https://github.com/onflow/cadence/releases/tag/v1.0.0-M8)
> Update to Cadence v1.0.0-M8

- decode_test.go
- evm_location.go
Closes: https://github.com/onflow/flow-go-sdk/issues/576
The code is taken from: https://github.com/onflow/flow-go/blob/master/fvm/evm/types/events.go#L33-L97, and after merging this PR, the `flow-go` repository should be updated to use this `EVMLocation` defined here.
______
> Add a custom location for `EVM` and register a `TypeID` Decoder

- access/grpc/client.go
Closes: #577 
I will cherry pick this to a PR on the master branch after merged.
______
> Add WaitServer method

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.18](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.18)
> Update to Cadence v1.0.0-preview.18

- README.md
- go.mod
- go.sum
- upgrade `onflow/crypto`
- clarify build constraints related to https://github.com/onflow/crypto when using the module. This also addresses https://github.com/onflow/crypto/issues/7.
> Upgrade `onflow/crypto` and clarify build details

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.21](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.21)
> Update to Cadence v1.0.0-preview.21

- flow.go
- transaction.go
Closes: #631 
Fixes panic if transaction arguments are empty (`release/v0`) branch
______
> Fix panic when encoding transaction with empty arguments (`release/v0`)

- flow.go
- transaction.go
Closes: #631 
Fixes panic if transaction arguments are empty
______
> Fix panic when encoding transaction with empty arguments

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.25](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.25)
> Update to Cadence v1.0.0-preview.25

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.26](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.26)
> Update to Cadence v1.0.0-preview.26

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.27](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.27)
> Update to Cadence v1.0.0-preview.27

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.28](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.28)
> Update to Cadence v1.0.0-preview.28

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.29](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.29)
> Update to Cadence v1.0.0-preview.29

- access/grpc/client.go
- access/grpc/grpc.go
- access/grpc/grpc_test.go
- decode.go
- test/entities.go
Closes: #666 
Currently, event encoding is hard coded to use CCF. This was added to switch to the smaller size payloads. However, it does not support backwards compatibility mode needed by some clients during the Cadence 1.0 transition.
This PR updates the grpc client code to allow setting the event encoding for the client. During the transition, users can switch to use JSONCDC.
______
> Make event encoding configurable over grpc

- .github/workflows/ci.yml
- go.mod
- go.sum
Cadence and flow-go have been updated to Go 1.22 already.
______
> Update to Go 1.22

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.36](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.36)
> Update to Cadence v1.0.0-preview.36

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.38](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.38)
> Update to Cadence v1.0.0-preview.38

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.46](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.46)
> Update to Cadence v1.0.0-preview.46

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.47](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.47)
> Update to Cadence v1.0.0-preview.47

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.48](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.48)
> Update to Cadence v1.0.0-preview.48

- go.mod
- go.sum
- [onflow/cadence v1.0.0-preview.49](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.49)
> Update to Cadence v1.0.0-preview.49

- access/grpc/client.go
- access/grpc/grpc.go
Closes: #???
Currently, there's no way to get the execution data client used by the SDK client. This is sometimes useful when the SDK is not fully up to date with the access API. 
Adding a `ExecutionDataRPCClient()` method to return the raw client
______
> Add method to get execution data client

- access/grpc/client.go
- access/grpc/grpc.go
- access/grpc/grpc_test.go
- access/grpc/mocks/RPCClient.go
- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
> Add GetAccountBalance endpoint to grpc server

- access/grpc/convert/convert.go
- test/entities.go
- transaction.go
> Add computation_usage to transaction result response object

- access/grpc/client.go
- access/grpc/convert/convert.go
- access/grpc/grpc.go
- access/grpc/grpc_test.go
> Add SubscribeBlockHeaders* endpoints

- access/grpc/grpc.go
- access/grpc/grpc_test.go
- flow.go
> Update GetNodeVersionInfo response object

- access/grpc/convert/convert.go
- examples/go.mod
- examples/go.sum
fix for https://github.com/onflow/flow-go/pull/6571#issuecomment-2428866323
> timeout certificate can be nil

- access/grpc/grpc.go
- access/grpc/grpc_test.go
- examples/send_and_subscribe_transaction_statuses/main.go
Closes: [#6604](https://github.com/onflow/flow-go/issues/6604)
* Implements an example of `SendAndSubscribeTransactionStatuses` on the testnet, as the emulator does not support subscriptions.  
* The `messageIndex` value has been fixed, as it should always start at 1.
> [Access] Fix SendAndSubscribeTransactionStatuses and example

- access/grpc/convert/convert.go
- transaction.go
- transaction_test.go
Closes: #???
Adds 2 new functions to allow adding signatures with extension data.
Also uses these functions in the grpc convert message step
______
> Improve passkeys integration, to allow adding signatures with extension data
